// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Angular17WithASP.Core.Entities;

public partial class Opportunity
{
    public int Id { get; set; }

    public int ContactId { get; set; }

    public string Name { get; set; }

    public decimal Price { get; set; }

    public virtual Contact Contact { get; set; }
}