// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Angular17WithASP.Core.Entities;

public partial class Contact
{
    public int Id { get; set; }

    public string AssignedTo { get; set; }

    public string Company { get; set; }

    public string Email { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Name { get; set; }

    public string Phone { get; set; }

    public string Position { get; set; }

    public string Status { get; set; }

    public string Image { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public int? StateId { get; set; }

    public int? ZipCode { get; set; }

    public virtual ICollection<Activity> Activities { get; set; } = new List<Activity>();

    public virtual ICollection<Opportunity> Opportunities { get; set; } = new List<Opportunity>();

    public virtual State State { get; set; }

    public virtual ICollection<Task> Tasks { get; set; } = new List<Task>();
}