// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Angular17WithASP.Core.Entities;

public partial class State
{
    public int StateId { get; set; }

    public string StateShort { get; set; }

    public string StateLong { get; set; }

    public string StateCoords { get; set; }

    public string Flag48px { get; set; }

    public string Flag24px { get; set; }

    public byte[] SsmaTimeStamp { get; set; }

    public virtual ICollection<Contact> Contacts { get; set; } = new List<Contact>();
}